### ISSUE TITLE
Calculate doppler shift.

### ISSUE THREAD

**Issue by johngian** [satnogs/satnogs-client#21]
We need to implement a method to calculate the doppler shift and amend the functionality of ``WorkerFreq.send_to_socket`` method.

**Comment by johngian** [comment]
@adamkalis wanted to take a shot at this.

**Comment by jinxcat** [comment]
Apparent frequency =  Real frequency * v / (v + v(s))

where:
v = speed of light =299792458 m/s 
v(s) = range_velocity of satellite

**Comment by jinxcat** [comment]
It would be great to have reference values, so we can verify the correctness of calculations. 

@ppapadeas @papamat suggestions? Does gpredict or a similar tool offer verified doppler shift?

**Comment by alexschultze** [comment]
I have seen discussions that the range velocity differs between XEphem and Gpredict in the range of 5-6%. (Maybe because of atmospheric refraction).
http://stackoverflow.com/questions/23551019/range-rate-for-doppler-calculation-and-atmospheric-refraction-compensation?rq=1

On the quick I couldnt find a comparison of the prediction tools available .. probably it stays a religious thing until somebody does the math. ;-)

**Comment by alexschultze** [comment]
First of all, I just figured out that for electromagnetic waves the doppler equation is different.
Longitudinal 
f_o * sqrt ((c+v) / (c - v))

Second, PyEphem does not calculate the correct velocities (however other values are calculated correctly).
I have fixed that here, so it should be fixed in one of the next releases. 
https://github.com/brandon-rhodes/pyephem/pull/76

**Comment by aincrad** [comment]
Thank you Alex. Is there any way to know which release it is coming out at?
Or shall we just read the changelog?

**Comment by johngian** [comment]
@alexschultze We can always add the dependency from their git repo when this gets merged (no need to wait for a release). Thank you for the upstream work.

**Comment by johngian** [comment]
Hey @alexschultze !

This issue is currently one of our major priorities. Can you help us with that since it looks like you have more insight?

**Comment by alexschultze** [comment]
I have now contacted brandon rhodes with a request to make a version increment just now. I am very certain that the new velocity values are OK. Temporarily you could build your own pyephem from this git.
https://github.com/alexschultze/pyephem

**Comment by alexschultze** [comment]
Note that the correct equation is:
fd=f*(c-v)/(c+v) is the correct equation to use, with v<0 range velocity when the distance is reducing, as is the default output of libastro.

Latest information here:
Brandon is in the progress of making a new release of pyephem for use. The values are only of by a scale factor btw.

**Comment by johngian** [comment]
Fixed in #56.
